In [11]:
# Hands on Numpy Training
import sys
import numpy as np

np.array([1,2,3,4])

array([1, 2, 3, 4])

In [2]:
a = np.array([1,2,3,4])
b = np.array([0,.5,1,1.5,2])
a[0], a[1]

(1, 2)

In [5]:
a[0:]
b[0:]

array([0. , 0.5, 1. , 1.5, 2. ])

In [8]:
another_list = ['Hello', 'my', 'best', 'old', 'friend']
print(another_list[-2])
print(another_list[-1])

old
friend


In [13]:
# DIMENION AND SHAPE
A = np.array([
    [1,2,3,4], 
    [5,6,7,8]
    ])
A.shape

(2, 4)

In [14]:
A.size

8

In [15]:
A.ndim

2

In [16]:
B = np.array([
#    0, 1, 2 
    [2, 3, 4], # 0
    [7, 8, 9], # 1
    [0, -1, 4] # 2
])
B.size

9

In [30]:
B.sum()

AttributeError: 'builtin_function_or_method' object has no attribute 'sum'

In [32]:
x = np.array([1, 2,3, 5])
x.size

4

In [33]:
x.sum()

11

In [35]:
# broadcasting and vectoring operations
z = np.arange(4)
z

array([0, 1, 2, 3])

In [36]:
z + 20

array([20, 21, 22, 23])

In [37]:
z

array([0, 1, 2, 3])

In [38]:
z += 20

In [39]:
z

array([20, 21, 22, 23])

In [40]:
z -= 20
z

array([0, 1, 2, 3])

In [41]:
z[[True, False, False, True]]

array([0, 3])

In [ ]:
# PANDAS a a library that wwill aid in all the DA process
